# Supply Chain Analytics

### Data Cleaning and Preprocessing

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../data/raw/dataco_supply_chain.csv', encoding='latin-1')
df.shape

(180519, 53)

In [3]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-02-03 22:56:00,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-18 12:27:00,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-17 12:06:00,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-16 11:45:00,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2018-01-15 11:24:00,Standard Class

In [4]:
df.dtypes

Type                              object
Days for shipping (real)           int64
Days for shipment (scheduled)      int64
Benefit per order                float64
Sales per customer               float64
Delivery Status                   object
Late_delivery_risk                 int64
Category Id                        int64
Category Name                     object
Customer City                     object
Customer Country                  object
Customer Email                    object
Customer Fname                    object
Customer Id                        int64
Customer Lname                    object
Customer Password                 object
Customer Segment                  object
Customer State                    object
Customer Street                   object
Customer Zipcode                 float64
Department Id                      int64
Department Name                   object
Latitude                         float64
Longitude                        float64
Market                            object
Order City                        object
Order Country                     object
Order Customer Id                  int64
order date (DateOrders)           object
Order Id                           int64
Order Item Cardprod Id             int64
Order Item Discount              float64
Order Item Discount Rate         float64
Order Item Id                      int64
Order Item Product Price         float64
Order Item Profit Ratio          float64
Order Item Quantity                int64
Sales                            float64
Order Item Total                 float64
Order Profit Per Order           float64
Order Region                      object
Order State                       object
Order Status                      object
Order Zipcode                    float64
Product Card Id                    int64
Product Category Id                int64
Product Description              float64
Product Image                     object
Product Name                      object
Product Price                    float64
Product Status                     int64
shipping date (DateOrders)        object
Shipping Mode                     object
dtype: object

In [5]:
df.isnull().sum()

Type                                  0
Days for shipping (real)              0
Days for shipment (scheduled)         0
Benefit per order                     0
Sales per customer                    0
Delivery Status                       0
Late_delivery_risk                    0
Category Id                           0
Category Name                         0
Customer City                         0
Customer Country                      0
Customer Email                        0
Customer Fname                        0
Customer Id                           0
Customer Lname                        8
Customer Password                     0
Customer Segment                      0
Customer State                        0
Customer Street                       0
Customer Zipcode                      3
Department Id                         0
Department Name                       0
Latitude                              0
Longitude                             0
Market                                0
Order City                            0
Order Country                         0
Order Customer Id                     0
order date (DateOrders)               0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Item Profit Ratio               0
Order Item Quantity                   0
Sales                                 0
Order Item Total                      0
Order Profit Per Order                0
Order Region                          0
Order State                           0
Order Status                          0
Order Zipcode                    155679
Product Card Id                       0
Product Category Id                   0
Product Description              180519
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [6]:
df[['order date (DateOrders)', 'shipping date (DateOrders)']].dtypes

order date (DateOrders)       object
shipping date (DateOrders)    object
dtype: object

In [7]:
df[['order date (DateOrders)', 'shipping date (DateOrders)']].head()

  order date (DateOrders) shipping date (DateOrders)
0     2018-01-31 22:56:00        2018-02-03 22:56:00
1     2018-01-13 12:27:00        2018-01-18 12:27:00
2     2018-01-13 12:06:00        2018-01-17 12:06:00
3     2018-01-13 11:45:00        2018-01-16 11:45:00
4     2018-01-13 11:24:00        2018-01-15 11:24:00

In [8]:
df["order_date"]    = pd.to_datetime(df["order date (DateOrders)"], errors="coerce")
df["shipping_date"] = pd.to_datetime(df["shipping date (DateOrders)"], errors="coerce")

In [9]:
print(df[['order_date', 'shipping_date']].dtypes)
print(df.isnull().sum().sum(), "missing values remaining")

order_date       datetime64[ns]
shipping_date    datetime64[ns]
dtype: object
336209 missing values remaining

In [10]:
#Clean column names
df = df.drop(columns=[
    "Product Description",
    "Order Zipcode",
    "Customer Email",
    "Customer Password",
    "Customer Fname",
    "Customer Lname",
    "Customer Street",
    "Product Image"
])

In [11]:
df.isnull().sum().sum()

np.int64(3)

In [12]:
df.shape

(180519, 47)

In [13]:
df.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Id', 'Customer Segment', 'Customer State',
       'Customer Zipcode', 'Department Id', 'Department Name', 'Latitude',
       'Longitude', 'Market', 'Order City', 'Order Country',
       'Order Customer Id', 'order date (DateOrders)', 'Order Id',
       'Order Item Cardprod Id', 'Order Item Discount',
       'Order Item Discount Rate', 'Order Item Id', 'Order Item Product Price',
       'Order Item Profit Ratio', 'Order Item Quantity', 'Sales',
       'Order Item Total', 'Order Profit Per Order', 'Order Region',
       'Order State', 'Order Status', 'Product Card Id', 'Product Category Id',
       'Product Name', 'Product Price', 'Product Status',
       'shipping date (DateOrders)', 'Shipping Mode', 'order_date',
       'shipping_date'],
      dtype='object')

In [14]:
#clean column names
df.columns = (df.columns.str.strip()
            .str.lower()
            .str.replace(' ', '_')
            .str.replace('(', '')
            .str.replace(')', '')
            )

In [15]:
df.dtypes

type                                   object
days_for_shipping_real                  int64
days_for_shipment_scheduled             int64
benefit_per_order                     float64
sales_per_customer                    float64
delivery_status                        object
late_delivery_risk                      int64
category_id                             int64
category_name                          object
customer_city                          object
customer_country                       object
customer_id                             int64
customer_segment                       object
customer_state                         object
customer_zipcode                      float64
department_id                           int64
department_name                        object
latitude                              float64
longitude                             float64
market                                 object
order_city                             object
order_country                          object
order_customer_id                       int64
order_date_dateorders                  object
order_id                                int64
order_item_cardprod_id                  int64
order_item_discount                   float64
order_item_discount_rate              float64
order_item_id                           int64
order_item_product_price              float64
order_item_profit_ratio               float64
order_item_quantity                     int64
sales                                 float64
order_item_total                      float64
order_profit_per_order                float64
order_region                           object
order_state                            object
order_status                           object
product_card_id                         int64
product_category_id                     int64
product_name                           object
product_price                         float64
product_status                          int64
shipping_date_dateorders               object
shipping_mode                          object
order_date                     datetime64[ns]
shipping_date                  datetime64[ns]
dtype: object

In [16]:
# Create shipping delay
df['shipping_delay'] = (df['days_for_shipping_real'] - df['days_for_shipment_scheduled'])

In [17]:
df['shipping_delay'].describe()

count    180519.000000
mean          0.565807
std           1.490966
min          -2.000000
25%           0.000000
50%           1.000000
75%           1.000000
max           4.000000
Name: shipping_delay, dtype: float64

In [18]:
# Convert numeric columns
df["order_item_total"] = pd.to_numeric(
    df["order_item_total"], errors="coerce"
    )

In [19]:
# order_month and is_late are derived columns
df["order_month"] = df["order_date"].dt.to_period("M").astype(str)
df["is_late"]     = df["late_delivery_risk"] == 1

In [20]:
df.to_csv("../data/processed/clean_supply_chain.csv", index=False)
print(f"saved {len(df):,} rows x {len(df.columns)} columns")
print("order_date range:", df["order_date"].min().date(), "to", df["order_date"].max().date())

saved 180,519 rows x 50 columns
order_date range: 2015-01-01 to 2018-01-31